# Generated by Django 2.0.2 on 2020-03-29 15:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='citizen',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('adhar', models.BigIntegerField(max_length=16, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('migrated', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='donate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=50)),
                ('amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cost', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cost', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('date', models.DateField()),
                ('place', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('caused', models.CharField(max_length=30)),
                ('migrated', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='required',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date(2020, 3, 29))),
                ('place', models.CharField(max_length=30)),
                ('required', models.CharField(max_length=50)),
                ('required1', models.CharField(max_length=30)),
                ('quality', models.IntegerField(max_length=10)),
                ('feedback', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='spent_on',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=30)),
                ('quality', models.IntegerField(max_length=10)),
                ('Total', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='stay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('cost', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='citizen',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.region'),
        ),
    ]
