# Generated by Django 2.0.2 on 2021-01-11 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='required',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 12)),
        ),
    ]
