# Generated by Django 2.0.2 on 2019-11-24 13:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fund', '0002_auto_20191113_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='current_amount',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 24, 18, 46, 29, 906913)),
        ),
        migrations.AlterField(
            model_name='donate',
            name='date',
            field=models.DateField(default=datetime.date(2019, 11, 24)),
        ),
        migrations.AlterField(
            model_name='region',
            name='date',
            field=models.DateField(default=datetime.date(2019, 11, 24)),
        ),
        migrations.AlterField(
            model_name='required',
            name='date',
            field=models.DateField(default=datetime.date(2019, 11, 24)),
        ),
    ]
