# Generated by Django 2.0.2 on 2019-11-25 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_auto_20191124_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.RenameField(
            model_name='spent_on',
            old_name='amount',
            new_name='Total',
        ),
        migrations.AlterField(
            model_name='current_amount',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 26, 0, 27, 25, 748308)),
        ),
        migrations.AlterField(
            model_name='donate',
            name='date',
            field=models.DateField(default=datetime.date(2019, 11, 26)),
        ),
        migrations.AlterField(
            model_name='region',
            name='date',
            field=models.DateField(default=datetime.date(2019, 11, 26)),
        ),
        migrations.AlterField(
            model_name='required',
            name='date',
            field=models.DateField(default=datetime.date(2019, 11, 26)),
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
