# Generated by Django 2.0.2 on 2019-11-25 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_auto_20191126_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_amount',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 26, 0, 28, 45, 285381)),
        ),
    ]
