# Generated by Django 2.0.2 on 2019-12-15 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_auto_20191126_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_amount',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='donate',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='required',
            name='date',
            field=models.DateField(default=datetime.date(2019, 12, 15)),
        ),
    ]
