# Generated by Django 2.0.2 on 2019-12-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0006_auto_20191215_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='required',
            name='date',
            field=models.DateField(),
        ),
    ]
