# Generated by Django 2.0.2 on 2019-12-15 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0007_auto_20191215_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='required',
            name='date',
            field=models.DateField(default=datetime.date(2019, 12, 15)),
        ),
    ]
