# Generated by Django 2.0.2 on 2019-12-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0009_auto_20191218_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
