# Generated by Django 2.0.2 on 2019-12-21 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0010_auto_20191218_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='current_amount',
        ),
        migrations.AlterField(
            model_name='required',
            name='date',
            field=models.DateField(default=datetime.date(2019, 12, 21)),
        ),
    ]
